


import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import FirstPage from '../components/FirstPage'
import Router from 'next/router'
import  {useRouter}  from 'next/router';
import  {useEffect}  from 'react';

export default function Home() {
  return (
    <div className='h-full'>
      
      <Head>
        <title>circles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.png" />
      </Head>

      <Header />
      
      <FirstPage/>

    </div>
    
  )
}


